name: CI Production
on:
  push:
    branches: [master]
  # pull_request:
  #   branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 'v9.3.0'
      - name: Checkout app
        uses: actions/checkout@v2
        with:
          path: app-test
      - name: Build and Push the Image
        run: |
          TIMESTAMP=$(date +%s)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::386698934404:role/GithubActionsRole
          aws-region: eu-central-1
      - name: Get Github action IP
        id: ip
        uses: haythem/public-ip@v1.2
      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 \
            authorize-security-group-ingress \
            --group-id ${{ secrets.INSTANCE_SECURITY_GROUP_ID }} \ 
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          key: ${{ secrets.KEY }}
          source: "./app-test"
          target: "test"
          
