name: CI Production
on:
  push:
    branches: [master]
  # pull_request:
  #   branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 'v9.3.0'
      - name: Checkout app
        uses: actions/checkout@v2
        with:
          path: app-test
      - name: Build and Push the Image
        run: |
          ls 

          TIMESTAMP=$(date +%s)
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          key: ${{ secrets.KEY }}
          source: "./app-test"
          target: "test"
          
